// change layoute to template if you dont wanna preserve the component state and html elements

export const metadata = {
  title: {

    // this will override anything, also if this is in child component, it'll also ignore default and template title from the root
    absolute : "Absolute Next title",

    // when in child components, no title is provided
    default : "Next Playground",

    // title : "" in child component, title is replaced with %s and | Next Testing acts as prefix for title
    template : "%s | Next Testing"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p style={{ backgroundColor: "lightblue", color: "black" }} >Header</p>
        </header>
        {children}
        <footer>
          <p style={{ backgroundColor: "lightblue", color: "black" }} >Footer</p>
        </footer>
      </body>
    </html>
  )
}
